website/misc/views.py
from flask import Blueprint, render_template

misc = Blueprint('misc', __name__)


@misc.route("/")
@misc.route("/home")
def home():
	return render_template('index.html', title='Home')
	#this should render index.html but since the inheritence isn't set up on it, using base.html instead.
	#return render_template('index.html', title='Home')


@misc.route("/privacyPolicy")
def privacyPolicy():
	return render_template('policy.html', title="Privacy Policy")


@misc.route("/termsOfUse")
def termOfUse():
	return render_template('termOfUse.html', title="Terms Of Use")

website/movies/views.py
import secrets
from flask import Blueprint, render_template, request, session, url_for, flash, redirect
from flask_login import current_user
from website import app, db
from website.models import User, Blacklist, Whitelist, Movies
import random 
import requests
from datetime import datetime, timedelta

movies = Blueprint('movies', __name__)

# the period of time for how long data is saved on the website
app.secret_key = "df78sf845s65fsf9sd5f2fg13513sdfsa"
app.permanent_session_lifetime = timedelta(minutes=10)


@movies.route("/searchMovies/", methods=['GET', 'POST'])
@movies.route("/searchMovies/page=<page>", methods=['GET', 'POST'])
def seeMovieReview(page = 1):
	# initialise the required data
	search_result = ""
	number_of_movies = 0
	number_of_received_movies = 0
	titles = []
	years = []
	IDs = []
	types = []
	posters = []
	error_message = ""

	if request.method == 'POST':
		# session saves the typed keyword
		session.permanent = True

		search_result = request.form.get("search").strip()
		
		if search_result:
			session["search"] = search_result
		else:
			# if nothing was typed when do not query the API
			session.pop("search", None)


	emptySearchBox = False
		
	# if anything was typed in the search bar when query the API to get movies by keyword
	# otherwise, query the other API to receive 5 random popular movies
	if "search" in session:
		try:
			number_of_movies = 20

			pages = list()
			page = int(page)

			pages.append(page*2-1)
			pages.append(page*2)

			search_result = session["search"]

			api_key = ""
			for i in range(2):
				respString = 'http://www.omdbapi.com/?s=' + search_result + api_key + str(pages[i]) 
				r = requests.get(respString) 
				dictionary = r.json()
				if dictionary['Response'] == 'True':
					data = dictionary["Search"]
					for movie in data:
						titles.append(movie['Title'])
						years.append(movie['Year'])
						IDs.append(movie['imdbID'])
						posters.append(movie['Poster'])

					number_of_received_movies = len(IDs)
				else:
					if not IDs:
						error_message = "Try again! None movies were found..."

		except Exception as e:
			error_message = "Try again! None movies were found..."
	else:
		try:
			emptySearchBox = True
			number_of_movies = 20

			this_year = datetime.now().year

			search_result = ""

			# get this and last two years movies
			this_years_movies = Movies.query.filter_by(year=this_year).all()
			movies = Movies.query.filter_by(year=this_year-1).all()
			movies += this_years_movies + Movies.query.filter_by(year=this_year-2).all()
			number = len(movies)

			found_movies = False

			# to make sure the loop terminates
			counter = 0
			while not found_movies and counter < 100:
				try:
					num = random.randint(1, number)
					movie = movies[num]

					if movie.movie_id not in IDs and movie.poster != 'N/A':
						titles.append(movie.title)
						years.append(movie.year)
						IDs.append(movie.movie_id)
						posters.append(movie.poster)

					if len(titles) == number_of_movies:
						found_movies = True
				
				except Exception as e:
					pass

				counter += 1

		except Exception as e:
			error_message = "Try again! None movies were found..."


	# validate if page data type is not a string
	try:
		page = int(page)
	except Exception as e:
		error_message = "Try again! Invalid page number was provided!"

	return render_template(
		'seeMovieReview.html',
	 	title='Search Movies',
	 	search_result=search_result,
	 	number_of_movies=number_of_movies,
		number_of_received_movies=number_of_received_movies,
	 	titles=titles,
	 	years=years,
	 	IDs=IDs,
	 	posters=posters,
	 	error_message=error_message,
	 	page=page,
	 	emptySearchBox=emptySearchBox)


def check_genres(checked_genres, number_of_checked_genres_boxes, copy_of_indices_of_checked_genres, names_of_genres, genres):
	if "checked" in checked_genres:
		for j in range(number_of_checked_genres_boxes):
			random.shuffle(copy_of_indices_of_checked_genres)
			if names_of_genres[copy_of_indices_of_checked_genres[-1]] in genres:
				return True
			else:
				copy_of_indices_of_checked_genres.remove(copy_of_indices_of_checked_genres[-1])

		return False
	else:
		return True


def check_movie_year(indices_of_checked_ranges_of_years, number_of_checked_ranges_of_years_boxes, 
					number_of_different_ranges_of_years, ranges_of_years, year_of_movie):
	# check if the movie appears in the selected range(s) of years, if any were selected
	if 0 not in indices_of_checked_ranges_of_years and number_of_checked_ranges_of_years_boxes != 0:
		for x in range(number_of_checked_ranges_of_years_boxes):
			years = ranges_of_years[indices_of_checked_ranges_of_years[x]]
			
			# check if not the last range was selected
			if indices_of_checked_ranges_of_years[x] != number_of_different_ranges_of_years-1:
				if years[0] <= year_of_movie <= years[1]:
					return True
			else:
				if years > year_of_movie:
					return True
		return False
	else:
		return True


def check_movie_language(languages_texts, number_of_checked_language_boxes, 
					number_of_different_languages, indices_of_checked_languages, movie_language):
	# check if the movie is in the selected language(s), if any were selected
	if 0 not in indices_of_checked_languages and number_of_checked_language_boxes != 0:
		for x in range(number_of_checked_language_boxes):
			language = languages_texts[indices_of_checked_languages[x]]
			if language in movie_language:
				return True

		return False
	else:
		return True


def check_db_for_movie(movie, blacklisted_movies_ids, indices_of_checked_genres,
						languages_texts, number_of_checked_language_boxes, number_of_different_languages, 
						indices_of_checked_languages, checked_genres, number_of_checked_genres_boxes, names_of_genres,
						indices_of_checked_ranges_of_years, number_of_checked_ranges_of_years_boxes, 
						number_of_different_ranges_of_years, ranges_of_years, chosen_rating):

	# check if that movie is not in the blacklist
	# if it is, then skip this movie
	if blacklisted_movies_ids:
		if movie.movie_id in blacklisted_movies_ids:
			return False

	copy_of_indices_of_checked_genres = indices_of_checked_genres.copy()

	if movie.year == 0 or movie.genres == "" or type(movie.year) == str:
		return False

	found_language = check_movie_language(languages_texts, number_of_checked_language_boxes, 
					number_of_different_languages, indices_of_checked_languages, movie.language)

	if not found_language:
		return False

	found_corresponding_genre = check_genres(checked_genres, number_of_checked_genres_boxes, copy_of_indices_of_checked_genres, names_of_genres, movie.genres)
	
	if not found_corresponding_genre:
		return False

	found_movie_within_year_range = check_movie_year(
										indices_of_checked_ranges_of_years, 
										number_of_checked_ranges_of_years_boxes, 
										number_of_different_ranges_of_years,
										ranges_of_years, 
										movie.year)
		
	if not found_movie_within_year_range:
		return False

	if movie.rating == "N/A" and chosen_rating != 0 or movie.poster == "" or movie.poster == "N/A":
		return False

	return True


@movies.route("/suggestMeMovies", methods=['GET', 'POST'])
def suggestMeMovies():
	# the tuples and lists to save the required data for criteria

	names_of_genres = ("Action", "Adventure", "Animation", "Biography", "Comedy", "Crime", 
						"Documentary", "Drama", "Family", "Fantasy", "History", "Horror", 
						 "Mystery", "Romance", "Sci-Fi", "Thriller")

	indices_of_checked_genres = []
	number_of_different_genres = len(names_of_genres)
	checked_genres = [""]*number_of_different_genres


	ratings = (0, 7, 6.5, 6, 5.5, 5, 4.5)
	ratings_texts = ("Any Ratings", "Rated over 7",
					"Rated over 6.5","Rated over 6","Rated over 5.5",
					"Rated over 5", "Rated over 4.5")
	chosen_rating = 0
	number_of_different_ratings = len(ratings)


	languages_identifiers = (0, 1, 2, 3, 4)
	languages_texts = ("Any Language", "English",
					"French","Japanese","Spanish")
					
	number_of_different_languages = len(languages_identifiers)
	indices_of_checked_languages = []
	checked_languages = [""]*number_of_different_languages


	ranges_of_years_text = ("All years", "2010 – now", "2000 – 2009", "1990 – 1999",
							"1980 – 1989", "1960 – 1979", "Older than 1960")

	ranges_of_years = (0, (2010, 2021), (2000, 2009), (1990, 1999),
					  (1980, 1989), (1960, 1979), 1960)

	indices_of_checked_ranges_of_years = []
	number_of_different_ranges_of_years = len(ranges_of_years_text)
	checked_ranges_of_years = [""]*number_of_different_ranges_of_years

	# executes when the button "generate the movie" was pressed
	# this code encures that the selected criteria does not reset after every refresh of the page
	if request.method == 'POST':
		# session saves the checked criteria if the page was left
		session.permanent = True

		chosen_rating = float(request.form.get('Ratings'))
		session["chosen_rating"] = chosen_rating

		for i in range(number_of_different_genres):
			if request.form.get(names_of_genres[i]):
				indices_of_checked_genres.append(i)
				checked_genres[i] = "checked"
				session["checked_genres" + str(i)] = "checked"
			else:
				if ("checked_genres" + str(i)) in session:
					session.pop("checked_genres" + str(i), None)

		for i in range(number_of_different_ranges_of_years):
			if request.form.get(ranges_of_years_text[i]):
				indices_of_checked_ranges_of_years.append(i)
				checked_ranges_of_years[i] = "checked"
				session["checked_ranges_of_years" + str(i)] = "checked"
			else:
				if ("checked_ranges_of_years" + str(i)) in session:
					session.pop("checked_ranges_of_years" + str(i), None)
		
		for i in range(number_of_different_languages):
			if request.form.get(languages_texts[i]):
				indices_of_checked_languages.append(i)
				checked_languages[i] = "checked"
				session["checked_languages" + str(i)] = "checked"
			else:
				if ("checked_languages" + str(i)) in session:
					session.pop("checked_languages" + str(i), None)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- page naming -->
    {% if title %}
        <title>{{ title }} - FILMFLICK</title>
    {% else %}
        <title>FILMFLICK</title>
    {% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- meta data -->
    <meta name="author" content="Group W2">
    <meta name="description" content="The movie suggestion website">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<style>
  @font-face {
    font-family: 'ProximaNovaBold';
    src: url(../static/Proxima_Nova_Bold.otf);
    font-style: normal;
    font-weight: 100;
  }
  *{
    margin: 0;
    padding: 0;
    font-family: ProximaNovaBold;
  }
  body::-webkit-scrollbar {
    width: 5px;
  }
  body::-webkit-scrollbar-track {
    background: none;
  }
  body::-webkit-scrollbar-thumb {
    background-color: grey;
    border-radius: 20px;
    border: none;
  }
  .navbar a {
    color: white;
  }
  footer a,p{
    color: white;
  }
  
  a:hover {
    color: #6ABCEA;
  }
  .navbar-toggler {
    color: white;
  }



</style>

<body>
      <!-- navbar and shared html elements to be inserted here -->
    <nav class="navbar navbar-expand-md bg-dark sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{ url_for('misc.home') }}"><img src="{{url_for('static', filename='logo2_w2.png')}}" alt="FILMFLICK" width="150" height="40"></a>
      <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('misc.home') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('movies.suggestMeMovies') }}">Suggest Me Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('movies.seeMovieReview') }}">Search Movies</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('usersReviews.account') }}">My Profile</a>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('usersReviews.logout') }}">Logout</a>
          {%else%}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('usersReviews.register') }}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('usersReviews.login') }}">Login</a>
          </li>
          {%endif%}
        </ul>
      </div>
    </div>
    </nav>
    <div class="col-md-8">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{category}}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
    </div>
    {% block content %}{% endblock %}

    <footer>
      <div class="container-fluid padding bg-dark p-3" id="footer">
        <div class="col-12 text-center">
          <!-- can add the hyperlink for the terms of use and privacy policy to the respective text below -->
          <!-- placeholder links for t&c and policies -->
          <p>While using FILMFLICK, you agree to have read and accepted our <a href="{{ url_for('misc.termOfUse')}}">Terms of Use</a> and <a href="{{ url_for('misc.privacyPolicy')}}">Privacy Policy</a>.</p>
          <p>Data regarding Movies provided by <a href="http://www.omdbapi.com/">OMDB API</a>. All content licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC BY-NC 4.0</a>.</p>
          <p>&copy; FILMFLICK 2020-2021. All Rights Reserved.</p>
          <p class="font-weight-light">By Group W2</p>
          <hr class="light">
          <a href="#">Return to Top</a>
        </div>
      </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script type="text/javascript" src="../static/background.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</script crossorigin="anonymous"></script>
    <script type="text/javascript" src="../static/background.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

website/templates/forgot_password.html
{% extends "base.html" %}
{% block content %}


<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

<!-- below is just some styling i added to help me visualise the page, they can be removed/put into a stylesheet -->
     <style>
      *{
        box-sizing: border-box;

      }

      html {
        height: 100%;
      }

      body{
        background: #FF8870;
        min-height: 100%;
        background-image: url("../static/background2.png");
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed

      }
      a:hover {
        color: #6ABCEA;
      }
      .container{
        margin-top: 100px;
        display: flex;
        flex-direction: column;
        height: 150vh;
        animation: fadein 1.5s;

      }

      #register {
        flex: 1 0 auto;
      }

      .row{
        background: white;
        border-radius: 30px;
      }
      img{
        border-top-left-radius: 30px;
        border-bottom-left-radius: 30px;
      }
      .submit-btn{
        border: none;
        outline: none;
        height: 50px;
        width: 100%;
        background-color: black;
        color: white;
        border-radius: 4px;
        font-weight: bold;
      }
      .submit-btn:hover{
        background:white;
        border:1px solid;
        color: black;
      }

      label{
        width: 240px;
        display: inline-block;
      }
      #footer {
        height: 218px;
        flex-shrink: 0;
      }
      .btn-primary{
        background-color: white;
        color: black;
        padding: 5px;
        border-color: black;
        margin-top: 30px;
        margin-bottom: 100px
      }
      .btn-primary:hover{
        background-color: grey;
        border:1px solid;
        color: white;
      }
      .btn-primary.active, .btn-primary:active, .show>.btn-primary.dropdown-toggle {
        background-color: grey;
        border:1px solid;
        color: white;
      }
      #leftimagediv {
        background-color: #EB197F;
        border-top-left-radius: 30px;
        border-bottom-left-radius: 30px;
      }
      h1 {
        color: transparent;
      }
      .input-field{
        padding-bottom: 5px;
      }
      @media (max-width: 1000px){
        #leftimagediv {
          display: none;
        }
        .img-fluid {
          display: none;
        }
        #footer {
          height: 345px;
          /*display: none;*/
        }
        #register {
          padding: 0;
        }
        #fgtpassword {
          padding-bottom: 15px;
        }
        h1 {
          color: #FF8870;
        }
        #content {
          margin-bottom: 200px;
        }
        .container {
          height: 130vh;
          padding: 5px;
        }

      }
      @keyframes fadein {
        from { opacity: 0}
        to   { opacity: 1}
      }



    </style>


    </style> 
    <!-- image and register forms -->
    <section class="Form mx-5 my-4">
      <div class="container" id="forgotpassword">
        <div class="row no-gutters">
          <div class="col-lg-5">
            <img src="{{url_for('static', filename='poster.png')}}" class="img-fluid" alt="someimage">          
          </div>
          <div class="col-lg-7 px-5 pt-5">
            <h1 class="font-weight-bold py-3">FilmFlick</h1>
            <h2>Recover Password</h2>
            <br>
            <form class="form-signin" method="POST" action=" ">
              {{ form.hidden_tag() }}
              <!-- username input field -->
              <div class="form-row"> 
                <div class="col-lg-9">
            <fieldset class="form-group">
                  {{ form.username.label }}
                  {% if form.username.errors %}
                      {{ form.username(class="input-field")}} 
                      <div class="invalid-feedback"> 
                       {% for error in form.username.errors %}
                        <span>{{ error }} </span> 
                        {% endfor %} 
                      </div>
                    {% else %}
                      {{ form.username }}
                    {% endif %} 
                </div>
              </div>
              <!-- question_1 input field -->
              <div class="form-row">
                <div class="col-lg-9">
               <div class="input-field">
                      {{ form.question_1.label}}
                      {% if form.question_1.errors %}
                          {{ form.question_1 }}
                          <div class="invalid-feedback">
                            {% for error in form.question_1.errors %}
                                <span> {{ error}} </span>
                            {% endfor %} 
                          </div>
                          {% else %}
                            {{ form.question_1}} 
                            {% endif %}
                  
                </div>
                <!-- question_2 input field -->
              <div class="form-row">
                <div class="col-lg-9">
               <div class="input-field">
                      {{ form.question_2.label}}
                      {% if form.question_2.errors %}
                          {{ form.question_2 }}
                          <div class="invalid-feedback">
                            {% for error in form.question_2.errors %}
                                <span> {{ error}} </span>
                            {% endfor %} 
                          </div>
                          {% else %}
                            {{ form.question_2}} 
                            {% endif %}
                  
                </div>
                <!-- question_3 input field -->
              <div class="form-row">
                <div class="col-lg-9">
               <div class="input-field">
                      {{ form.question_3.label}}
                      {% if form.question_3.errors %}
                          {{ form.question_3 }}
                          <div class="invalid-feedback">
                            {% for error in form.question_3.errors %}
                                <span> {{ error}} </span>
                            {% endfor %} 
                          </div>
                          {% else %}
                            {{ form.question_3}} 
                            {% endif %}
                  
                </div>
                <!-- question_1 input field -->
              <div class="form-row">
                <div class="col-lg-9">
               <div class="input-field">
                      {{ form.password.label}}
                      {% if form.password.errors %}
                          {{ form.password }}
                          <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span> {{ error}} </span>
                            {% endfor %} 
                          </div>
                          {% else %}
                            {{ form.password}} 
                            {% endif %}
                  
                </div>    
                
             <!-- login button -->
                <div >
                    {{ form.submit_forgot_password (class="submit-btn mt-3 mb-5")}} 
              </div>
              
              </div>
            </form>
        </div>
      </div>
    </section>



    <!-- jQuery first, then Tether, then Bootstrap JS. -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

{% endblock content %}

website/templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
  body{
    height: 100vh;
    background: #FF8870;
    background-image: url("../static/background2.png");
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed
  }
  .container{
    background: none;
    height: 100vh;
    width: 100%;
    overflow-x: hidden;
  }
  .container h1{
    font-size: 9vw;
    color: transparent;
    text-transform: uppercase;
    position: relative;
    padding-top: 20px;
    display: block;
    transform: translateX(10%)
    transform: translateY(40%);
  }

  .container h1:before{
    padding-top: 20px;
    content: attr(data-text);
    position: absolute;
    top:0;
    left:0;
    width: 100%;
    height: 100%;
    color: white;
    overflow: hidden;
    animation: animate 2s linear infinite;
  }
  h3 {
    color: white;
    padding: 15px 0 20px 0;
  }
  #suggestbtn{
    background: none;
    border-width: 6px;
    border-color: white;
    border-radius: 15px;
    padding: 10px;
    border-style: solid;
    color: white;
    margin-bottom: 10px;
  }
  #suggestbtn:hover{
    background:white;
    border:6px solid;
    color: #FF8870;
  }
  #textvertical{
    animation: fadein 1.5s;
  }

  .linebreak{
    border-top: 8px solid white;
    border-radius: 5px;
  }
  button{
    font-family: ProximaNovaBold;
  }
  @keyframes animate{
    0%,10%,100%{
      width: 0;
    }
    70%,90%{
      width:100%;
    }
  }
  @keyframes fadein {
    from { opacity: 0}
    to   { opacity: 1}
  }

</style>
<div class="container" id="textvertical">
  <div class="row-4">
    <div class="col-12">
      <br><br><br><br><br><br><br><br>
        <h1 data-text="FilmFlick//"><span>FilmFlick</span></h1>
        <div>
        <h3>Can't find a film to watch? We've got you covered. &#128252;</h3>
        <form action="{{ url_for('movies.suggestMeMovies') }}">
          <input id="suggestbtn" type="submit" value="Suggest a Movie" />
        </form>
        <br>
      </div>
    </div>
  </div>
</div>



{% endblock content %}